# Generated by Django 4.1.2 on 2022-10-07 12:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('nome_foto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('categoria', models.CharField(max_length=100)),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
    ]
