# Generated by Django 4.1.2 on 2022-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_usuario_fotografia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='imagem',
            field=models.ImageField(upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
